<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="TP6_GRUPO_17.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Trabajo Práctico N°6 - Grupo 17</h1>
            <nav>
                <a href="Ejercicio1.aspx">Ejercicio 1</a> |
                <a href="Ejercicio2.aspx">Ejercicio 2</a>
            </nav>
            <h2>Ejercicio 1</h2>

            <h2>Productos</h2>
            <asp:GridView ID="gvProductos" runat="server" AllowPaging="True" AutoGenerateColumns="False" OnPageIndexChanging="gvProductos_PageIndexChanging" AutoGenerateDeleteButton="True" OnRowDeleting="gvProductos_RowDeleting">
                <Columns>
                    <asp:TemplateField HeaderText="Id">
                        <ItemTemplate>
                            &nbsp;<asp:Label ID="lbl_it_id" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                            &nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <ItemTemplate>
                            &nbsp;<asp:Label ID="lbl_it_nombre" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:Label>
                            &nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad x Unidad">
                        <ItemTemplate>
                            &nbsp;<asp:Label ID="lbl_it_cantidadPorUnidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:Label>
                            &nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio x Unidad">
                        <ItemTemplate>
                            &nbsp;<asp:Label ID="lbl_it_precioPorUnidad" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:Label>
                            &nbsp;
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
